* E-stitches May meet-up Barcelona / THURSDAY, MAY 20, 2021 AT 6 PM UTC+03

Facebook link: [[https://www.facebook.com/events/472751800698708?acontext=%7B%22event_action_history%22%3A[%7B%22mechanism%22%3A%22search_results%22%2C%22surface%22%3A%22bookmark%22%7D]%7D]]

THURSDAY, MAY 20, 2021 AT 6 PM UTC+03

Free   · Online Event
Details
Event by Emilie Giles and E-Stitches London
Online Event
Thursday, May 20, 2021 at 6 PM UTC+03
Price: Free
Public  · Anyone on or off Facebook
We are kicking off the first e-stitches Barcelona with 3 talks on embodiment, performance and e-textiles in STEAM. Join us this Thursday!
Topic: E-stitches Barcelona
Time: May 20, 2021 5pm Madrid time/ 4pm UK time
https://us02web.zoom.us/j/84071231775...
Meeting ID: 840 7123 1775
Passcode: e-stitches
We are inviting you to the kick-off e-stitches barcelona talks
Citlali Hernández (Mexico City, 1986)
Industrial Designer at UNAM; Master in Digital Arts at the Universitat Pompeu Fabra; Fab Academy at IaaC Fab Lab Barcelona.
Citlali focuses her work on the body as a space for research in artistic practices that through diverse multimedia formats, relate the experience of the body and the use of technology from a critical perspective. Some of her projects have been presented in various spaces and festivals, including: CCEMx (Cd.Mx), CMMAS (Morelia), GAM Cultural Center (Santiago de Chile), L'Estruch Cultural Center (Sabadell), Sala OFF (Valencia ), Contemporary Art Fair JustMAD 15 and 17 (Madrid), Mercat de les Flors (Barcelona), ECOSS Festival 18 and 19 (Barcelona), VERTEX Video Art Festival (Medellín), among others. Currently, and in collaboration with Nuria Nia (Matics Barcelona), she is doing an artistic residency at Hangar (Center for Artistic Research in Barcelona) developing the project "Satelite Bodies" centered on the tensions between data and body over the Internet. Citlali is also dedicated to teaching digital fabrication and interaction, and is a doctoral student at the Centro Universitario de Diseño BAU with the theme “Body, Technology and Performativity: The body in the practices of new media art”.
http://www.turbulente.net/
https://www.instagram.com/turbulente/
--------------------------------------------------------------------------------------------------------------
Agustina Palazzo is an Argentinean artist with a degree in Audiovisual Design from the Blas Pascal University with a Master in New Media and interactive technologies from the IAAC (Institute of Advanced Architecture of Catalonia.)
Her practice oscillates between art, education and cultural management in the context of the digital world and new technologies. Fluctuating between a critical and poetic vision, she takes communication technologies and human behavior as the basis for her creation and thinking. With a multidisciplinary attitude, between performance, sound design and objects she uses new technologies as creative tools. Based in Barcelona she is a professor of Digital Creation and Wearables technologies at ESDIo Escola Superior de disseny and she has participated in solo and group exhibitions, festivals and residencies around Latin America and Europe.
IG | LKDN
www.agustinapalazzo.com
--------------------------------------------------------------------------------------------------------------
Paola Guimeráns is an E-textiles education specialist and an Interaction Design and Wearable Technology expert. She holds a BFA major at the University of Seville, an MFA Design + Technology at Parsons School of Design, New York. and a Ph.D. major at the Complutense University of Madrid. My Ph.D studies examined how the improvements that have taken place in the field of e-textiles provide new opportunities for research and learning in what visual arts concerns, with the use of digital technologies and electronics.Since 2013, I have taught and developed interdisciplinary STEAM curricula focused on e-textiles and Wearable Electronics. Among other projects, I am the founder of the innovative educational technology project Aula STEAM:E-textiles and Education and the author of the online e-textile DIY resources platform written in Spanish PrototipadoLAB.
https://paolaguimerans.com/
http://aulasteam.com/
http://prototipadolab.com/ See Less
Online
