
* Βρόχοι: Λούπες ή Βρόχοι Ανάδρασης;

** Λούπα, επανάληψη, κυκλικές φόρμες

Στο περασμένο μάθημα έγινε συζήτηση για την έννοια του βρόχου - με αφορμή την παρατήρηση ότι ο Lev Manovic θεωρεί τον βρόχο σαν βασική έννοια στην εξέλιξη των νέων μέσων και ιδιαίτερα στον προγραμματισμό.  Στη συζήτηση, ο βρόχος συνδέθηκε με την έννοια της λούπας όπως την ξέρουμε από την σύγχρονη ηλεκτρονική και άλλη μουσική.  Συζητήθηκε η εννοιολογική συνάφεια της έννοιας με τον κύκλο και την έννοια της ανανέωσης. Αυτή πάλι συνυφαίνεται και με την μονιμότητα, την στάση, και κατ επέκταση την αιωνιότητα.  Μιλήσαμε για μια γνωστή φράση από την ιστορία της δυτικής φιλοσοφίας, που αναφέρεται στην αιωνιότητα: Το "sub specie aeternitatis" του Baruch Spinoza, που είναι γιαυτόν κριτήριο για να φτάσει κανείς στην ουσία μιας έννοιας ανεξάρτητα από χρονικές ή τοπικές μεταβολές.  

Έγινε επίσης αναφορά στο φιλοσοφικό έργο του Gilles Deleuze "Difference and Repetition" (1968. Γαλλικά: "Différence et Répétition"), και την σημασία της επανάληψης τόσο για την αντίληψη της διαφοράς και της αλλαγής όσο και για την αναίρεσή τους.  Από αυτή την άποψη είναι αξίζει να εξετάσει κανείς πως χρησιμοποιούνται επαναλαμβανόμενα μελωδικά μοτίβα ή ακολουθίες συγχορδιών στη μουσική σαν βασικό δομικό στοιχείο, και ιδιαίτερα πως αντιπαρατίθενται με άλλα στοιχεία για να δημιουργήσουν την αίσθηση της κίνησης ή της αιώρησης στο χρόνο και της στάσης.

Η ιδέα του κύκλου έχει κια μια δέυτερη σημασία και μορφογενετικό ρόλο στην μουσική όσο και στην αφήγηση. Η έννοια του κυκλικού χρόνου είναι συνδεδεμένη με την αιωνιότητα και με θεωρίες περί σύμπαντος και ψυχής στον Ινδουϊσμό και τον Βουδισμό, που θεωρεί ότι η ύπαρξη του ανθρώπου όπως και όλων των έμβιων όντων υπόκειται σε κύκλους μετεψύχωσης με τελικό στόχο τη λύτρωση. Παρόμοιες δοξασίες αντηχούν και στους ώριμους διαλόγους του Πλάτωνα, καθώς και στην Πολιτεία του, στον μύθο του Ηρός, που μιλά για την αθανασία της Ψυχής. Αυτός ο μύθος ενέπνευσε το έργο ηλεκτρονικής του Ιάνη Ξενάκη "La Légende d'Eer".

https://www.youtube.com/watch?v=TNWFITZrvxo

Παραδείγματα κυλικής φόρμας που τελειώνει με την επιστροφή στην αρχή, επαναλαμβάνοντας στοιχεία από αυτήν στο τέλος, βρίσκονται σε πολλά στάδια στην εξέλιξη της δυτικής μουσικής. Χαρακτηριστικό παράδειγμα είναι η τριμερής φόρμα (ternary form, https://en.wikipedia.org/wiki/Ternary_form).  Υπάρχουν πολλές παραλλαγές και εξελίξεις αυτής ιδιαίτερα από τον 19ο αιώνα και πέρα.  Επιπλέον παρατηρήται η κυκλική φόρμα και στην αφήγηση, διαχρονικά.  Χαρακτηριστικά παραδείγματα: 

1. Το έπος του Gilgamesh (Μεσοποταμία, ~2000 Πχ), ξεκινά και τελειώνει την αφήγηση με την προτροπή στον σύντροφο του αφηγήματος να ανεβεί στα τείχη της πόλης που δημιούργησε ο Gilgamesh και να την περιεργαστεί. Αυτό συνοδεύεται και από έμμεσες αναφορές σε δύο κεντρικά προβλήματα του έργου, δηλαδή την θνησιμότητα (το αδύνατο της αθανασίας), και την μετάδοση της γνώσης.  Χαρακτηριστικό επίσης είναι ότι το γραπτό κείμενο - η καταγραφή των άθλων του Gilgamesh σε κείμενο που ασφαλίζεται σε κιβώτιο - αποτελεί μεταφορικά την λύση του προβλήματος, καθότι μεταδίδει γνώση και διασφαλίζει την συνέχιση της μνήμης του ήρωα (αν και όχι την παράταση της φυσικής του ζωής).

- Διάλεξη του Andrew George: Συζήτηση του ρόλου του τελικού χωρίου με την περιγραφή της πόλης https://youtu.be/Rd7MrGy_tEg?t=3424
- Διάλεξη του Steve Tinney: Συζήτηση άλλων στοιχείων που διασυνδέουν το κείμενο (πήλινο πινάκιο καταγραφής) με τη στήλη σαν μνημείο που διατηρεί αθάνατη τη μνήμη των βασιλέων  https://youtu.be/46Xst2do8p4?t=2627

2. Το διήγημα επιστημονικής φαντασίας του Isaak Asimov "The Last Question", τελειώνει την αφήγηση με ένα reset του Σύμπαντος στην αρχή, με την εντολή του υπολογιστή "Γεννηθήτω φως", σε απάντηση προς το ερώτημα εάν είναι δυνατή η αναστροφή του νόμου της εντροπείας. (Διαβάστε το διήγημα σε pdf στα έγγραφα του μαθήματος).  Σημειωτέον ότι η συνεχής αναδημιουργία νέων παραλλήλων συμπάντων προβλέπετα σσε πρόσφατα εξεταζόμενα μοντέλα της Κοσμολογίας. (Μικρή επιλογή από πολλά βίντεος στο Youtube: https://www.youtube.com/watch?v=ANCN7vr9FVk  https://www.youtube.com/watch?v=cEijLstRLg8 https://www.youtube.com/watch?v=K_FUlo8BF9Y. ). 

** Βρόχος ανάδρασης: Feedback loop

Μετά το μάθημα σκέφτηκα ότι πιθανόν ο Lev Manovic δεν αναφερόταν στον βρόχο σαν απλή επανάληψη ("iteration", "do-loop"), αλλά σαν βρόχο ανατροφοδότησης της εξόδου στην είσοδο κατά την επανάληψη της εφαρμογής μιας διαδικασίας ή συνάρτησης ("feedback loop", "recursion". βλ. https://www.translatum.gr/forum/index.php?topic=187993.0).  Αυτό οδηγεί σε μια ξεχωριστή κατηγορία διαδικασιών και τεχνολογιών που συνδέονται με γλώσσες προγραμματισμού όπως το LISP, το Haskell, και το Julia (https://riptutorial.com/julia-lang/example/10466/recursive-functions).  Επίσης, η προσέγγιση αυτή συνδέεται άμεσα με την μελέτη μη-γραμμικών συστημάτων και τις θεωρίες των fractals και του Χάους.  Χαρακτηριστικό παράδειγμα μιας recursive function είναι ο η συνάρτηση του αριθμού Fibonacci, και η πρώτη σωζόμενη διατύπωσή της από τον Ινδό μαθηματικό Hemachandra με την μοφρή ποιήματος δείχνει πως προέκυψε ο αριθμός σαν απόδειξη της μεθόδου για την παραγωγή όλων των δυνατών συνδυασμών βραχέων και μακρών συλλαβών σε έναν στίχο με ν συλλαβές.  

Ιδιαίτερα ενδιαφέρουσα είναι η χρήση του feedback στην σύνθεση και επεξεργασία του ήχου.  Σε αυτήν βασίζεται μια σειρά από τεχνικές που παίζουν σημαντικό ρόλο στην σύνθεση ήχου και στην ψηφιακή/ηλεκτρονική μουσική και μουσική υπολογιστική. 

*Μένει να διασαφηνισθεί σε ποιά από τις δύο έννοιες αναφέρεται ο Lev Manovic στο έργο του!* Πρόσθεσα στα αρχεία του μαθήματος μια επισκόπηση του βιβλίου του Manevic για τα νέα μέσα. Δεν έχω βρεί όμως ακόμη την αναφορά στο βρόχο που αναφέρθηκε στο προηγούμενο μάθημα. 

* Επικείμενη στροφή προς πρακτικές ασκήσεις

Η παραπάνω ύλη, μαζί με αυτά που είδαμε στα προηγούμενα μαθήματα έχει εκτενέστατες προεκτάσεις και τόσα πολλά παραδείγματα, που θα μπορούσε εύκολα να γεμίσει όλο το εξάμηνο.  Όμως το πλαίσιο του μαθήματος δεν το επιτρέπει, γιατι πρέπει να δούμε το θέμα και από τεχνική και τεχνολογική σκοπιά.  Γιαυτό, από το επόμενο μάθημα θα αρχίσουμε να βλέπουμε πως προγραμματίζει κανείς ήχο στο SuperCollider, αλλά και στο FoxDot, (https://foxdot.org/) ενα άλλο περιβάλλον που βασίζεται στην γλώσσα Python και συνεργάζεται με το SuperCollider για την παραγωγή ήχου. 
